server {
    listen 80;
    server_name localhost;

    # A raiz do nosso projeto é a pasta public, onde o index.php está.
    root /var/www/html/public;
    index index.php;

    # Trata todas as requisições.
    location / {
        # Tenta encontrar um arquivo com o nome da URL ($uri).
        # Se não encontrar, tenta encontrar uma pasta com o nome ($uri/).
        # Se falhar em ambos, envia a requisição para o index.php.
        # Isso faz com que o nosso Router do Symfony controle todas as páginas.
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Passa os scripts PHP para o container do PHP-FPM para execução.
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # Conecta-se ao container PHP na porta 9000.
        fastcgi_pass php:9000;

        fastcgi_index index.php;
        include fastcgi_params;

        # Diz ao PHP qual arquivo executar.
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Bloqueia o acesso a arquivos sensíveis.
    location ~ /\.ht {
        deny all;
    }
}

